version: '3.3'
services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306
    #volumes:
    #  - ../DockerVolumes/mariadb:/var/lib/mysql
    #  - /home/$USER/docker/mariadb:/var/lib/mysql

