version: '3.3'
services:
  mongo:
    image: mongo:4.2.3
    container_name: mongo-rs2
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
    ports:
      - 27017:27017
    #volumes:
    #  - /home/$USER/docker/mongo:/data/db
    #  - ../DockerVolumes/mongodb:/data/db
    command: ['mongod', '--replSet', 'rs0']
  mongo-setup:
    image: mongo:4.2.3
    container_name: mongo-rs2-setup
    depends_on:
      - mongo
    command:  bash -c 'sleep 5 && /usr/bin/mongo --host mongo --eval "rs.initiate()"'
