version: '3.3'
services:
  mongo:
    image: mongo:4.0.0
    container_name: mongo-rs
    #environment:
    #  - MONGO_INITDB_ROOT_USERNAME=root
    #  - MONGO_INITDB_ROOT_PASSWORD=pass
    ports:
      - 27017:27017
    command: ["mongod", "--replSet", "rs0"]
