version: '3.3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306
    #volumes:
    #  - ../DockerVolumes/mysql:/var/lib/mysql
    #  - /home/$USER/docker/mysql:/var/lib/mysql

