services:
  postgresql:
    image: postgres:18-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=db
      - POSTGRES_ENCODING=UTF-8
    ports:
      - 5432:5432
    volumes:
      - /home/kacper/Dev/docker-volumes/postgres/data:/var/lib/postgresql/data

