services:
  timescaledb:
    image: timescale/timescaledb:latest-pg17
    container_name: timescaledb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=esp32
    ports:
      - "5432:5432"
    volumes:
      - /home/kacper/Dev/docker-volumes/timescaledb/data:/var/lib/postgresql/data
