[[inputs.mqtt_consumer]]
  servers = ["tcp://mosquitto:1883"]
  topics = ["iot/+/data"]
  name_override = "iot_data"
  data_format = "json"
  tag_keys = ["device_id", "app"] 

[[inputs.mqtt_consumer]]
  servers = ["tcp://mosquitto:1883"]
  topics = ["iot/+/log"]
  name_override = "iot_logs"
  data_format = "json"
  tag_keys = ["device_id", "app", "level"]
  json_string_fields = ["msg"]

[[outputs.postgresql]]
  namepass = ["iot_data"]
  connection = "host=timescaledb user=postgres password=pass dbname=iot sslmode=disable"
  schema = "public"
  tags_as_foreign_keys = false
  timestamp_column_name = "time"
  timestamp_column_type = "timestamp without time zone"
  fields_as_jsonb = true

[[outputs.postgresql]]
  namepass = ["iot_logs"]
  connection = "host=timescaledb user=postgres password=pass dbname=iot sslmode=disable"
  schema = "public"
  tags_as_foreign_keys = false
  timestamp_column_name = "time"
  timestamp_column_type = "timestamp without time zone"
  fields_as_jsonb = false
  
